### ISSUE TITLE
Frequency part is not updated 

### ISSUE THREAD

**Issue by SauravDas90** [sourabc9/Leetcode-Company-Questions-2020---2021-#1]
Hi @sourabc9 , why is the frequency part locked?

**Comment by sourabc9** [comment]
Hey I tried to print the page as save to pdf, and just noticed that we cannot show the frequency bar when saving page to pdf. But as mentioned, problems are sorted according to frequency in descending manner.

**Comment by SauravDas90** [comment]
Ok, what happens when you save the page as html? Does the frequency gets printed then? Or may be you can take screen clipping?

**Comment by sourabc9** [comment]
I tried that, but it was taking tremendous amount of time, so I switch to saving as pdf.

**Comment by SauravDas90** [comment]
IF you be kind enough to share only for FAANG, it will be great
